# Add seed data here. Seed your database with `rake db:seed`

asap = Artist.create(name: "A$AP")
action_bronson = Artist.create(name: "Action Bronson")
adele = Artist.create(name: "Adele")
araabmuzik = Artist.create(name: "AraabMuzik")
atlas_sound = Artist.create(name: "Atlas Sound")
azealia_banks = Artist.create(name: "Azealia Banks")
battles = Artist.create(name: "Battles")
beyonce = Artist.create(name: "Beyonce")

dance = Genre.create(name: "Dance")
indie = Genre.create(name: "Indie")
folk = Genre.create(name: "Folk")
country = Genre.create(name: "Country")
pop = Genre.create(name: "Pop")
hip_hop = Genre.create(name: "Hip-Hop")
rock = Genre.create(name: "rock")
house = Genre.create(name: "House")


Song.create(name: "Ricky Peso", artist: asap)
Song.create(name: "Larry Csonka", artist: action_bronson)
Song.create(name: "Rolling In the Deep", artist: adele)
Song.create(name: "Someone Like You", artist: adele)
Song.create(name: "Streetz Tonight", artist: araabmuzik)
Song.create(name: "Mona LIsa", artist: atlas_sound)
Song.create(name: "212", artist: azealia_banks)
Song.create(name: "Ice Cream", artist: battles)
Song.create(name: "1+1", artist: beyonce)
Song.create(name: "Countdown", artist: beyonce)